import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/components/provider/AuthProvider";
import AppProvider from "@/components/provider/AppProvider";
import {Manrope} from "next/font/google"
import { ThemeProvider } from "next-themes";
// import localFont from "next/font/local";

// ✅ DO NOT export this font
// const helvetica = localFont({
//   src: "./fonts/HelveticaNeueBold.otf",
//   variable: "--font-helvetica",
//   weight: "100 200 300 400 500 600 700 800 900", 
//   display: "swap",
// });

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-manrope",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Splurjj",
  description: "Generated by splurjj description",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.className} antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <AppProvider>
              {children}
              <Toaster position="top-right" />
              <ToastContainer />
            </AppProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
